version: "3.4"
services:
 vite-docker:
   image: node:alpine
   container_name: vite-docker
   entrypoint: /bin/sh
   ports:
     - 8000:8000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./vue-app
       target: /srv/app
   tty: true
